import Vue from 'vue';

Vue.component('TabType1', () => import('./_tab-type-1.vue'))
Vue.component('TabType2', () => import('./_tab-type-2.vue'))
Vue.component('TabType3', () => import('./_tab-type-3.vue'))
Vue.component('TabType4', () => import('./_tab-type-4.vue'))
Vue.component('TabType5', () => import('./_tab-type-5.vue'))
Vue.component('TabType6', () => import('./_tab-type-6.vue'))
Vue.component('TabType7', () => import('./_tab-type-7.vue'))
Vue.component('TabType8', () => import('./_tab-type-8.vue'))
Vue.component('TabType9', () => import('./_tab-type-9.vue'))
Vue.component('TabType10', () => import('./_tab-type-10.vue'))
Vue.component('TabType11', () => import('./_tab-type-11.vue'))
Vue.component('TabType12', () => import('./_tab-type-12.vue'))
Vue.component('TabType13', () => import('./_tab-type-13.vue'))
Vue.component('TabType14', () => import('./_tab-type-14.vue'))
